#!/bin/bash
GRAPHDIR="$1"
LOGDIR="$2"
HOSTPORT="$3"

GRAPH_W=500
GRAPH_H=300

if [ -z "$GRAPHDIR" -o -z "$LOGDIR" -o -z "$HOSTPORT" ]; then
    echo "Usage: $0 graph_dir log_dir hostport"
    exit 1
fi

n=$(date +%Y%m%d%H)
curl http://$HOSTPORT/$n.log > $LOGDIR/$n.log

basedir=$(dirname "$0")
$basedir/update-rrd.py --history_file $LOGDIR/history.pickle \
    $LOGDIR $LOGDIR/*.log

$basedir/make-graphs.py $LOGDIR $GRAPHDIR
