#!/bin/bash
GRAPHDIR="$1"
LOGDIR="$2"
HOSTPORT="$3"

GRAPH_W=500
GRAPH_H=300

if [ -z "$GRAPHDIR" -o -z "$LOGDIR" -o -z "$HOSTPORT" ]; then
    echo "Usage: $0 graph_dir log_dir hostport"
    exit 1
fi

subst_file=""
do_subst=0
if [ -e "$GRAPHDIR/index.tmpl" ]; then
    subst_file="$GRAPHDIR/index.html.new"
    cp "$GRAPHDIR/index.tmpl" "$subst_file"
    do_subst=1
fi

n=$(date +%Y%m%d%H)
curl http://$HOSTPORT/$n.log > $LOGDIR/$n.log

basedir=$(dirname "$0")
$basedir/update-rrd.py $LOGDIR $LOGDIR/*.log

for hours in 4 12 24 48 168; do
    # Meter does 166 and 2/3 revs per kWh == 6Wh per rev.
    # 21600 = 6 (Wh per rev) * 3600 (hour). revs coming out of the RRD is the
    # instantaneous rate at each time period, so multiplying by 21600 should
    # give instantaneous Wh use at each point.
	rrdtool graph $GRAPHDIR/power-${hours}h.png \
		--start end-${hours}h --lower-limit 0 \
		--title "Electrical Power Usage" \
		DEF:revs=${LOGDIR}/node1_revs.rrd:node1_revs:AVERAGE \
		--vertical-label Watts --width $GRAPH_W --height $GRAPH_H \
		CDEF:watts=revs,21600,\* LINE1:watts#ff0000:Power
    if [ $do_subst == 1 ]; then
        # Calculate total kWH usage shown on the graph, substitute if
        # requested.  Similar to above, multiply revs by 6, to get
        # instantaneous Wh use, then divide by 1k to get kWh and use the built
        # in TOTAL functionality to combine the instantaneous measurements
        # together.
        total=$(rrdtool graph /dev/null --start end-${hours}h \
            DEF:revs=${LOGDIR}/node1_revs.rrd:node1_revs:AVERAGE \
            CDEF:kWh=revs,6,\*,1000,\/ \
            VDEF:total_kWh=kWh,TOTAL \
            PRINT:total_kWh:%.2lf | tail -n1)
        sed -i "s/#total_kWh_${hours}h#/$total/" "$subst_file"
    fi

	rrdtool graph $GRAPHDIR/battery-${hours}h.png \
		--start end-${hours}h --lower-limit 0 --title "Battery voltage" \
        DEF:node1=${LOGDIR}/node1_bat.rrd:node1_bat:AVERAGE \
        DEF:node2=${LOGDIR}/node2_bat.rrd:node2_bat:AVERAGE \
        DEF:node3=${LOGDIR}/node3_bat.rrd:node3_bat:AVERAGE \
        DEF:node4=${LOGDIR}/node4_bat.rrd:node4_bat:AVERAGE \
        --vertical-label mV --width $GRAPH_W --height $GRAPH_H \
        CDEF:mv1=node1,50,\+,20,\* CDEF:mv2=node2,50,\+,20,\* \
        CDEF:mv3=node3,50,\+,20,\* CDEF:mv4=node4,50,\+,20,\* \
        LINE1:mv1#ff0000:PowerMeter LINE1:mv2#00ff00:Node2 \
        LINE1:mv3#0000ff:Node3 LINE1:mv4#ff8c00:Node4

    rrdtool graph $GRAPHDIR/temp-${hours}h.png \
        --start end-${hours}h --lower-limit 0 --title "Temperature" \
        DEF:lounge=/${LOGDIR}/node2_temp.rrd:node2_temp:AVERAGE \
        DEF:outside=${LOGDIR}/node3_temp.rrd:node3_temp:AVERAGE \
        DEF:bedroom=${LOGDIR}/node4_temp.rrd:node4_temp:AVERAGE \
        --vertical-label DegC --width $GRAPH_W --height $GRAPH_H \
        LINE1:outside#ff0000:Outside LINE1:lounge#00ff00:Lounge \
        LINE1:bedroom#0000ff:Bedroom
done

if [ $do_subst == 1 ]; then
    # Per node stats
    for n in $(seq 1 4); do
        # Battery Status
        value=$(rrdtool graph /dev/null \
            DEF:node=${LOGDIR}/node${n}_bat.rrd:node${n}_bat:LAST \
            CDEF:v=node,50,\+,20,\*,1000,\/ \
            PRINT:v:LAST:%.2lf | tail -n1)
        sed -i "s/#node${n}_battery#/$value/" "$subst_file"
        # Current Temperatures
        value=$(rrdtool graph /dev/null \
            DEF:temp=${LOGDIR}/node${n}_temp.rrd:node${n}_temp:LAST \
            PRINT:temp:LAST:%.2lf | tail -n1)
        sed -i "s/#node${n}_temp#/$value/" "$subst_file"
        # 24hr min/max/avg Temperatures
        value=$(rrdtool graph /dev/null --start end-24h \
            DEF:temp=${LOGDIR}/node${n}_temp.rrd:node${n}_temp:MIN \
            PRINT:temp:LAST:%.2lf | tail -n1)
        sed -i "s/#node${n}_24h_min#/$value/" "$subst_file"
        value=$(rrdtool graph /dev/null --start end-24h \
            DEF:temp=${LOGDIR}/node${n}_temp.rrd:node${n}_temp:MAX \
            PRINT:temp:LAST:%.2lf | tail -n1)
        sed -i "s/#node${n}_24h_max#/$value/" "$subst_file"
        value=$(rrdtool graph /dev/null --start end-24h \
            DEF:temp=${LOGDIR}/node${n}_temp.rrd:node${n}_temp:AVERAGE \
            PRINT:temp:LAST:%.2lf | tail -n1)
        sed -i "s/#node${n}_24h_avg#/$value/" "$subst_file"

    done
    mv "$subst_file" "${subst_file/.new/}"
fi
