#!/bin/bash
GRAPHDIR="$1"
LOGDIR="$2"
HOSTPORT="$3"

if [ -z "$GRAPHDIR" -o -z "$LOGDIR" -o -z "$HOSTPORT" ]; then
    echo "Usage: $0 graph_dir log_dir hostport"
    exit 1
fi

n=$(date +%Y%m%d%H)
curl http://$HOSTPORT/$n.log > $LOGDIR/$n.log

basedir=$(dirname "$0")
$basedir/update-rrd.py $LOGDIR $LOGDIR/*.log

for hours in 4 12 24 48 168; do
    # Meter does 166 and 2/3 revs per kWh == 6Wh per rev.
    # 21600 = 6 (Wh per rev) * 3600 (hour). revs coming out of the RRD is the
    # instantaneous rate at each time period, so multiplying by 21600 should
    # give instantaneous Wh use at each point.
	rrdtool graph $GRAPHDIR/power-${hours}h.png \
		--start end-${hours}h --lower-limit 0 \
		--title "Electrical Power Usage" \
		DEF:revs=${LOGDIR}/node1_revs.rrd:node1_revs:AVERAGE \
		--vertical-label Watts --width 800 --height 600 \
		CDEF:watts=revs,21600,\* LINE1:watts#ff0000:Power

	rrdtool graph $GRAPHDIR/battery-${hours}h.png \
		--start end-${hours}h --lower-limit 0 --title "Battery voltage" \
        DEF:node1=${LOGDIR}/node1_bat.rrd:node1_bat:AVERAGE \
        DEF:node2=${LOGDIR}/node2_bat.rrd:node2_bat:AVERAGE \
        DEF:node3=${LOGDIR}/node3_bat.rrd:node3_bat:AVERAGE \
        DEF:node4=${LOGDIR}/node4_bat.rrd:node4_bat:AVERAGE \
        --vertical-label mV --width 800 --height 600 \
        CDEF:mv1=node1,50,\+,20,\* CDEF:mv2=node2,50,\+,20,\* \
        CDEF:mv3=node3,50,\+,20,\* CDEF:mv4=node4,50,\+,20,\* \
        LINE1:mv1#ff0000:PowerMeter LINE1:mv2#00ff00:Node2 \
        LINE1:mv3#0000ff:Node3 LINE1:mv4#ff8c00:Node4

    rrdtool graph $GRAPHDIR/temp-${hours}h.png \
        --start end-${hours}h --lower-limit 0 --title "Temperature" \
        DEF:lounge=/${LOGDIR}/node2_temp.rrd:node2_temp:AVERAGE \
        DEF:outside=${LOGDIR}/node3_temp.rrd:node3_temp:AVERAGE \
        DEF:bedroom=${LOGDIR}/node4_temp.rrd:node4_temp:AVERAGE \
        --vertical-label DegC --width 800 --height 600 \
        LINE1:outside#ff0000:Outside LINE1:lounge#00ff00:Lounge \
        LINE1:bedroom#0000ff:Bedroom
done
