#!/bin/bash
GRAPHDIR="$1"
LOGDIR="$2"
HOSTPORT="$3"

GRAPH_W=500
GRAPH_H=300

if [ -z "$GRAPHDIR" -o -z "$LOGDIR" -o -z "$HOSTPORT" ]; then
    echo "Usage: $0 graph_dir log_dir hostport"
    exit 1
fi

function get() {
    local hour="$1"
    local t="$LOGDIR/.$hour.log.$$"
    curl http://$HOSTPORT/$hour.log > "$t"
    if [ "$?" == "0" -a -s "$t" ]; then
        mv "$t" $LOGDIR/$hour.log
    fi
    rm -f "$t"
}

if [ "$(date +%M)" == "00" ]; then
    # Last hour too
    n=$(date -d "-1 hour" +%Y%m%d%H)
    get $n
fi
n=$(date +%Y%m%d%H)
get $n

basedir=$(dirname "$0")
$basedir/update-rrd.py --state_dir $LOGDIR $LOGDIR/*.log
$basedir/update-sd.py --project mattbnz-gce-test \
    --house bowenst --state_dir $LOGDIR $LOGDIR/*.log

export TZ=Pacific/Auckland
$basedir/make-graphs.py $LOGDIR $GRAPHDIR
